"""test_memory_embedding

Revision ID: 86a536d3ece5
Revises: 305e4c8b7844
Create Date: 2026-06-15 19:40:48.645210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '86a536d3ece5'
down_revision: Union[str, Sequence[str], None] = '305e4c8b7844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
                    sa.Column(
                        'embedding',
                        Vector(dim=768),
                        nullable=True
                    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id')
    )
    op.create_index(op.f('ix_memory_embeddings_id'), 'memory_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_embeddings_id'), table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    # ### end Alembic commands ###
