"""add_learning_tracks

Revision ID: 903ce59b718d
Revises: e81f0948c07e
Create Date: 2026-06-19 18:40:10.849651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ce59b718d'
down_revision: Union[str, Sequence[str], None] = 'e81f0948c07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_tracks_id'), 'learning_tracks', ['id'], unique=False)
    op.add_column('study_logs', sa.Column('learning_track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_logs', 'learning_tracks', ['learning_track_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_logs', type_='foreignkey')
    op.drop_column('study_logs', 'learning_track_id')
    op.drop_index(op.f('ix_learning_tracks_id'), table_name='learning_tracks')
    op.drop_table('learning_tracks')
    # ### end Alembic commands ###
