"""add_notes_to_study_logs

Revision ID: 9de2f17eda3a
Revises: 3d0e118a4fdf
Create Date: 2026-06-12 16:42:24.296379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de2f17eda3a'
down_revision: Union[str, Sequence[str], None] = '3d0e118a4fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "study_logs",
        sa.Column(
            "notes",
            sa.String(),
            nullable=False,
            server_default=""
        )
    )

    op.alter_column(
        "study_logs",
        "notes",
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_logs', 'notes')
    # ### end Alembic commands ###
